### ISSUE TITLE
Keys management with helm secrets

### ISSUE THREAD

**Issue by gitkent** [zendesk/helm-secrets#140]
Hi guys, 

We are trying to define the way we manage the GPG keys to enc/dec the helm secrets. 

The idea is trying to avoid having to share one key across the team. Then we will create a master key for the helm secrets, any additional new member who need access to the helm secret, the new member will have to generate his/her own key pairs then provide us his/her public key and we sign/trust it so that the new member will be able to enc/dec with own key.

Options like `helm secrets add-user` might be helpful?

**Comment by jkroepke** [comment]
@gitkent Looks this is directly supported in sops. You could use key-groups. No additional commands required.

https://github.com/mozilla/sops#key-groups

**Comment by gitkent** [comment]
@jkroepke Thanks for that. It really helps. I will close this issue.
