### ISSUE TITLE
Decrypt secrets in a temporary folder

### ISSUE THREAD

**Issue by eddycharly** [zendesk/helm-secrets#151]
It would be useful when deploying several releases concurrently, as the first to finish will delete files that are in use by other release deployments.

**Comment by dsuievalov** [comment]
Hello @eddycharly, looks like you are looking for a variable [HELM_SECRETS_DEC_SUFFIX](https://github.com/zendesk/helm-secrets/blob/9a04a461e560939d237dcd4dd85e4b5570e2a1c2/secrets.sh#L5). If you define different values for each of the releases that runs in parallel - they all decrypt the same secrets under the different names.

**Comment by eddycharly** [comment]
Thanks, that could work indeed but not practical to use in a declarative world.
Anyway, I just use sops directly now and it’s fine.
Closing.
